#
# openapi.yaml is the OpenAPI specification for the Parsit dependency parsing service.
#

swagger: '2.0'

info:
  version: '2.0.0'
  title: parsit-api-spec

x-global-options:
  go_package: .;api

paths:
  /parse:
    post:
      description: Receives a text in Italian and returns its morpho-syntactic structure
      operationId: postForParsing
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: request
          required: true
          in: body
          description: Request to the parsing service
          schema:
            $ref: '#/definitions/Request'
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Response'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Request:
    type: object
    properties:
      text:
        type: string
        description: The text to parse
  Response:
    type: object
    properties:
      sentences:
        type: array
        description: List of sentences
        items:
          $ref: '#/definitions/Sentence'
  Sentence:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: The ID of the sentence
      score:
        type: number
        format: double
        description: Confidence of overall sentence attachments
      tokens:
        type: array
        description: List of tokens
        items:
          $ref: '#/definitions/Token'
  Token:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: ID of the token
      type:
        type: string
        description: Token type (one of WORD, WORD_TRACE, TRACE)
      form:
        type: string
        description: Form of the token as in the original text
      pos:
        type: string
        description: Coarse-grained part-of-speech tag
      position:
        type: string
        description: Index of the token (not the ID)
      start:
        type: integer
        format: int32
        description: Index of the first character of the token in the original text
      end:
        type: integer
        format: int32
        description: Index of the last character of the token in the original text
      head:
        type: integer
        format: int32
        description: Syntactic head (-1 for the ROOT)
      deprel:
        type: string
        description: Dependency relation
      score:
        type: number
        format: double
        description: Confidence for the syntactic attachment
        example: 0.89
      semantic:
        type: array
        description: List of semantic labels
        items:
          type: string
      coref:
        type: array
        description: List of tokens
        items:
          $ref: '#/definitions/Coreference'
      morpho:
        type: array
        description: List of possible morphological interpretations
        items:
          $ref: '#/definitions/Morphology'
  Coreference:
    type: object
    required:
      - sentenceId
      - tokenId
      - score
    properties:
      sentenceId:
        type: integer
        format: int32
        description: The target sentence ID
        example: 1
      tokenId:
        type: integer
        format: int32
        description: The target token ID
        example: 5
      score:
        type: number
        format: double
        description: Confidence for the coreference
        example: 0.89
  Morphology:
    type: object
    properties:
      lemma:
        type: string
        description: The lemma
      pos:
        type: string
        description: Part-of-speech tag
      gender:
        type: string
        description: Grammatical gender
      number:
        type: string
        description: Number
      person:
        type: string
        description: Person
      mood:
        type: string
        description: Verbal mood
      tense:
        type: string
        description: Verbal tense
      case:
        type: string
        description: Grammatical case
      degree:
        type: string
        description: Degree
      ctx_gender:
        type: string
        description: Grammatical gender in the sentence context
      ctx_number:
        type: string
        description: Number in the sentence context
      ctx_person:
        type: string
        description: Person in the sentence context
      ctx_mood:
        type: string
        description: Verbal mood in the sentence context
      ctx_voice:
        type: string
        description: Verbal voice in the sentence context
  Error:
    type: object
    properties:
      Message:
        type: string
